### ISSUE TITLE
Ensure that this is a PWA

### ISSUE THREAD

**Issue by maxbeizer** [maxbeizer/lot-size-calculator#4]
```[tasklist]
### Tasks
- [x] Web app manifest and service worker meet the installability requirements
- [x] Does not register a service worker that controls page and start_url
- [x] Configured for a custom splash screen
- [x] Sets a theme color for the address bar.
- [x] Content is sized correctly for the viewport
- [x] Has a `<meta name="viewport">` tag with width or initial-scale
- [x] Manifest doesn't have a maskable icon
```
